name: clang-tidy-review

on:
  push:
  pull_request:
    paths:
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 14
          platform: x64

      - name: Cache Qt
        uses: actions/cache@v3
        with:
          path: $HOME/Qt
          key: ${{ runner.os }}-qt-${{ hashFiles('**/requirements.txt') }}
          
      - name: Install Qt
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          pip install aqtinstall
          aqt install-qt linux desktop 6.8.0 --outputdir $HOME/Qt --modules qtbase
          
      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: CMake Generate
        run: cmake -B build -S .

      - name: Run clang-tidy
        uses: ZedThree/clang-tidy-review@v0.19.0
        id: review
        with:
          build_dir: build
          config_file: ".clang-tidy"
          exclude: "3rdpart/*, build/*"
